language: node_js

node_js:
- "lts/*"

notifications:
  email: false

before_install:
- npm i -g lerna@2.11.x gulp@4.0.0 gulp-cli@2.0.1 webpack@4.8.x jest
- lerna clean --yes

install:
- lerna bootstrap --hoist

script:
- npm run build && npm run test:coveralls

after_success:
- echo "Cheking TRAVIS_EVENT_TYPE is cron -> TRAVIS_EVENT_TYPE = $TRAVIS_EVENT_TYPE"
- test $TRAVIS_EVENT_TYPE = "cron" && BUILD_TAG="4.0.$TRAVIS_BUILD_NUMBER-nightly" && echo "Generate new BUILD_TAG = $BUILD_TAG"

before_deploy:
- TRAVIS_TAG=$BUILD_TAG
- bash generate_releases.sh
- echo Generated Releases for BUILD_TAG = $BUILD_TAG

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: releases/**/*
  skip_cleanup: true
  prerelease: true
  name: $BUILD_TAG
  body: This release is an early preview of the new Bot Framework Emulator. Please consider it to be experimental, and we'd love to hear your feedback.
  on:
    branch: v4
    condition: $BUILD_TAG

cache:
  directories:
  - "node_modules"
